<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/23
 * Time: 11:26
 */

namespace App\Model;



use App\Utility\Pool\MysqlObject;
use App\Utility\Pool\MysqlPool;
use App\Utility\Pool\RedisObject;
use App\Utility\Pool\RedisPool;
use EasySwoole\Component\Pool\PoolManager;
use EasySwoole\EasySwoole\Config;
use EasySwoole\Http\AbstractInterface\Controller;

class Base extends Controller{
    protected $db;
    protected $redis;

    public function __construct()
    {
        parent::__construct();
        $this->db = PoolManager::getInstance()->getPool(MysqlPool::class)->getObj(Config::getInstance()->getConf('MYSQL.POOL_TIME_OUT'));
        $this->redis = PoolManager::getInstance()->getPool(RedisPool::class)->getObj(Config::getInstance()->getConf('MYSQL.POOL_TIME_OUT'));
    }
    function getDb() :MysqlObject{
        return $this->db;
    }

    function getRedis() :RedisObject{
        return $this->redis;
    }

    function index(){}


    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub.
        PoolManager::getInstance()->getPool(MysqlPool::class)->recycleObj($this->db);
        PoolManager::getInstance()->getPool(RedisPool::class)->recycleObj($this->redis);
    }

    public static function check_arr($rs){
        foreach ($rs as $v) {
            if (!$v) {
                return false;
            }
        }
        return true;
    }
}